version: '3.8'

services:
  api:
    build:
      .
    
    ports:
      - "3000:3000"
    
    environment:
      MONGO_URI: mongodb://mongo:27017/blogdb
      PORT: 3000
      JWT_SECRET: chaveSuperSecreta 
    
    depends_on:
      - mongo
  
  mongo:
    image: 
      mongo:latest

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db
  
volumes:
    mongo-data:
