name: CI - Testes Automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3
      - name: Setup do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Instalar Dependências
        run: npm install
      - name: Rodar os Testes com Cobertura
        run: npm run test:coverage
        env:
          MONGO_URI: ${{ secrets.MONGO_URI_TEST }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}